export const PAKISTAN_CITIES = [
  { value: '', label: 'Select City *' },
  { value: 'Karachi', label: 'Karachi' },
  { value: 'Lahore', label: 'Lahore' },
  { value: 'Islamabad', label: 'Islamabad' },
  { value: 'Faisalabad', label: 'Faisalabad' },
  { value: 'Rawalpindi', label: 'Rawalpindi' },
  { value: 'Multan', label: 'Multan' },
  { value: 'Peshawar', label: 'Peshawar' },
  { value: 'Quetta', label: 'Quetta' },
  { value: 'Gujranwala', label: 'Gujranwala' },
  { value: 'Sialkot', label: 'Sialkot' },
  { value: 'Hyderabad', label: 'Hyderabad' },
  { value: 'Bahawalpur', label: 'Bahawalpur' },
  { value: 'Sargodha', label: 'Sargodha' },
  { value: 'Sukkur', label: 'Sukkur' },
  { value: 'Larkana', label: 'Larkana' },
  { value: 'Sheikhupura', label: 'Sheikhupura' },
  { value: 'Rahim Yar Khan', label: 'Rahim Yar Khan' },
  { value: 'Jhang', label: 'Jhang' },
  { value: 'Dera Ghazi Khan', label: 'Dera Ghazi Khan' },
  { value: 'Gujrat', label: 'Gujrat' },
  { value: 'Sahiwal', label: 'Sahiwal' },
  { value: 'Wah Cantonment', label: 'Wah Cantonment' },
  { value: 'Mardan', label: 'Mardan' },
  { value: 'Kasur', label: 'Kasur' },
  { value: 'Okara', label: 'Okara' },
  { value: 'Mingora', label: 'Mingora' },
  { value: 'Nawabshah', label: 'Nawabshah' },
  { value: 'Chiniot', label: 'Chiniot' },
  { value: 'Kotri', label: 'Kotri' },
  { value: 'Kamoke', label: 'Kamoke' },
  { value: 'Hafizabad', label: 'Hafizabad' },
  { value: 'Sadiqabad', label: 'Sadiqabad' },
  { value: 'Mirpur Khas', label: 'Mirpur Khas' },
  { value: 'Burewala', label: 'Burewala' },
  { value: 'Kohat', label: 'Kohat' },
  { value: 'Khanewal', label: 'Khanewal' },
  { value: 'Dera Ismail Khan', label: 'Dera Ismail Khan' },
  { value: 'Turbat', label: 'Turbat' },
  { value: 'Muzaffargarh', label: 'Muzaffargarh' },
  { value: 'Abbottabad', label: 'Abbottabad' },
  { value: 'Mandi Bahauddin', label: 'Mandi Bahauddin' },
  { value: 'Shikarpur', label: 'Shikarpur' },
  { value: 'Jacobabad', label: 'Jacobabad' },
  { value: 'Jhelum', label: 'Jhelum' },
  { value: 'Khanpur', label: 'Khanpur' },
  { value: 'Khairpur', label: 'Khairpur' },
  { value: 'Khuzdar', label: 'Khuzdar' },
  { value: 'Pakpattan', label: 'Pakpattan' },
  { value: 'Hub', label: 'Hub' },
  { value: 'Daska', label: 'Daska' },
  { value: 'Gojra', label: 'Gojra' },
  { value: 'Dadu', label: 'Dadu' },
  { value: 'Muridke', label: 'Muridke' },
  { value: 'Bahawalnagar', label: 'Bahawalnagar' },
  { value: 'Samundri', label: 'Samundri' },
  { value: 'Tando Allahyar', label: 'Tando Allahyar' },
  { value: 'Tando Adam', label: 'Tando Adam' },
  { value: 'Jaranwala', label: 'Jaranwala' },
  { value: 'Chishtian', label: 'Chishtian' },
  { value: 'Attock', label: 'Attock' },
  { value: 'Vehari', label: 'Vehari' },
  { value: 'Chakwal', label: 'Chakwal' },
  { value: 'Kamalia', label: 'Kamalia' },
  { value: 'Umerkot', label: 'Umerkot' },
  { value: 'Kot Addu', label: 'Kot Addu' },
  { value: 'Wazirabad', label: 'Wazirabad' },
  { value: 'Mansehra', label: 'Mansehra' },
  { value: 'Layyah', label: 'Layyah' },
  { value: 'Swabi', label: 'Swabi' },
  { value: 'Chaman', label: 'Chaman' },
  { value: 'Taxila', label: 'Taxila' },
  { value: 'Nowshera', label: 'Nowshera' },
  { value: 'Khushab', label: 'Khushab' },
  { value: 'Shahdadkot', label: 'Shahdadkot' },
  { value: 'Mianwali', label: 'Mianwali' },
  { value: 'Kabal', label: 'Kabal' },
  { value: 'Lodhran', label: 'Lodhran' },
  { value: 'Hasilpur', label: 'Hasilpur' },
  { value: 'Charsadda', label: 'Charsadda' },
  { value: 'Bhakkar', label: 'Bhakkar' },
  { value: 'Badin', label: 'Badin' },
  { value: 'Arif Wala', label: 'Arif Wala' },
  { value: 'Ghotki', label: 'Ghotki' },
  { value: 'Sambrial', label: 'Sambrial' },
  { value: 'Jatoi', label: 'Jatoi' },
  { value: 'Haroonabad', label: 'Haroonabad' },
  { value: 'Daharki', label: 'Daharki' },
  { value: 'Narowal', label: 'Narowal' },
  { value: 'Tando Muhammad Khan', label: 'Tando Muhammad Khan' },
  { value: 'Kamber Ali Khan', label: 'Kamber Ali Khan' },
  { value: 'Mirpur Mathelo', label: 'Mirpur Mathelo' },
  { value: 'Kandhkot', label: 'Kandhkot' },
  { value: 'Bhalwal', label: 'Bhalwal' }
]
